---
- name: install redis
  apt: name="redis-server" state=present

- name: configure redis
  template: src="etc/redis/redis.conf" dest="/etc/redis/redis.conf" owner=root group=root mode=0644
  notify: restart redis service