---
- name: setup repositories
  template: src="etc/apt/{{item}}" dest="/etc/apt/{{item}}" owner=root group=root mode=0644
  with_items:
    - sources.list
    - sources.list.d/backports.list
  register: apt_sources

- name: update APT cache
  apt: update_cache=yes
  when: apt_sources is changed

- name: install APT modules
  apt: name="apt-transport-https" state=present

