---
- name: create user group
  group: name="{{system_user_group}}" state=present

- name: create user
  user: name="{{system_user_user}}" group="{{system_user_group}}" shell="{{system_user_shell}}" createhome=yes home="{{system_user_home}}" state=present

- name: create user SSH directory
  file: path="{{system_user_home}}/.ssh" state=directory owner="{{system_user_user}}" group="{{system_user_group}}" mode=0700

- name: prepare user SSH keys
  copy: content="{{item.content}}" dest="{{item.path}}" owner="{{system_user_user}}" group="{{system_user_group}}" mode=0600
  no_log: True
  with_items:
    - path: "{{system_user_home}}/.ssh/id_rsa"
      content: "{{system_user_private_key}}"
    - path: "{{system_user_home}}/.ssh/id_rsa.pub"
      content: "{{system_user_public_key}}"
    - path: "{{system_user_home}}/.ssh/authorized_keys"
      content: "{{system_user_public_key}}"

