---
## debian notation of package name to be installed
nginx_package: "nginx-extras=1.14*"
## flag whether to prefer backports release, necesarry for newer nginx versions
nginx_package_prefer_backports: True
nginx_package_release: "{{ansible_lsb.codename}}{% if nginx_package_prefer_backports %}-backports{% endif %}"

nginx_user: "www-data"

#nginx_access_log: "/var/log/nginx/access.log"
#nginx_error_log: "/var/log/nginx/error.log error"

nginx_access_log: "syslog:server=unix:/dev/log,tag=nginx_access,nohostname"
nginx_error_log: "syslog:server=unix:/dev/log,tag=nginx,nohostname error"

nginx_stats_context: "stats"
nginx_stats_port: 8180

nginx_use_vhost_default: True

nginx_worker_processes: 4
nginx_worker_rlimit_nofile: -1

nginx_worker_connections: 768

nginx_server_tokens: False

nginx_keepalive_timeout: 65

nginx_gzip: True

nginx_client_max_body_size: "1m"

nginx_header_machine_id: "{{inventory_hostname_short.split('-') | last}}"