---
- name: Install required packages
  apt: name="{{ publisher_packages }}" state=present

- name: Configure fail2ban action
  template: src="etc/fail2ban/action.d/{{ item }}" dest="/etc/fail2ban/action.d/{{ item }}" owner=root group=root mode=0644
  with_items:
  - "redis-publisher.conf"
  notify: restart fail2ban service

- name: Create publisher script
  template: src="usr/local/sbin/publisher.py" dest="/usr/local/sbin/publisher.py" owner=root group=root mode=0755
