---
- name: configure rspamd site
  template: src="etc/nginx/sites-available/{{item}}" dest="/etc/nginx/sites-available/{{item}}" owner=root group=root mode=0644
  with_items:
    - "rspamd"
  notify: restart nginx service

- name: enable rspamd site
  file: src="/etc/nginx/sites-available/{{item}}" path="/etc/nginx/sites-enabled/{{item}}" state=link
  with_items:
    - "rspamd"
  notify: restart nginx service
